---
collections:
  - name: community.general
    version: 8.0.2
    source: https://galaxy.ansible.com
  - name: community.docker
    version: 3.12.1
    source: https://galaxy.ansible.com
roles:
  - name: geerlingguy.docker
    version: 4.1.1
  - name: geerlingguy.certbot
    version: 5.2.0
